# Generated by Django 2.0.3 on 2018-03-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180311_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '机构信息', 'verbose_name_plural': '机构信息'},
        ),
    ]
