# Generated by Django 2.0.3 on 2018-03-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180313_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('agency ', '培训机构'), ('person', '个人'), ('college', '高校')], default='Agency', max_length=50, verbose_name='机构类别'),
        ),
    ]
