# Generated by Django 2.0.3 on 2018-03-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20180314_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='adress',
            field=models.CharField(max_length=160, verbose_name='所在地址'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_company',
            field=models.CharField(max_length=50, verbose_name='就职公司/高校'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_positon',
            field=models.CharField(max_length=50, verbose_name='职务'),
        ),
    ]
