# Generated by Django 2.0.3 on 2018-03-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_teacher_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='work_positon',
            new_name='work_postion',
        ),
    ]
