# Generated by Django 2.0.3 on 2018-03-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseresource_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('initial', '初级'), (' medium', '中级'), ('advanced', '高级')], max_length=10, verbose_name='课程等级'),
        ),
    ]
