# Generated by Django 2.0.3 on 2018-03-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='0', max_length=20, verbose_name='课程类别'),
        ),
    ]
