# Generated by Django 2.0.3 on 2018-03-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180314_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=12, verbose_name='课程标签'),
        ),
    ]
