# Generated by Django 2.0.3 on 2018-03-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='视频时间(分钟数)'),
        ),
    ]
