# Generated by Django 2.0.3 on 2018-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20180329_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_new',
            field=models.CharField(default='', max_length=50, verbose_name='课程通知'),
        ),
    ]
