# Generated by Django 2.0.3 on 2018-03-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_eailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('femail', '女')], default='', max_length=6, verbose_name='性别'),
        ),
    ]
