# Generated by Django 2.0.3 on 2018-03-11 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180311_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='set_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], max_length=50, verbose_name='验证类型'),
        ),
    ]
