# Generated by Django 2.0.3 on 2018-03-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180311_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='seend_type',
            new_name='send_type',
        ),
    ]
