# Generated by Django 2.0.3 on 2018-03-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=50, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
