# Generated by Django 2.0.3 on 2018-03-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180313_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=100, verbose_name='验证码'),
        ),
    ]
