# Generated by Django 2.0.3 on 2018-03-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180313_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
