# Generated by Django 2.0.3 on 2018-03-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180313_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
