# Generated by Django 2.0.3 on 2018-03-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_emailverifyrecord_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default', upload_to='image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
