# Generated by Django 2.0.3 on 2018-03-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180314_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/default', null=True, upload_to='image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
