# Generated by Django 2.0.3 on 2018-03-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_loginbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', max_length=50, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(max_length=10, verbose_name='顺序'),
        ),
    ]
