# Generated by Django 2.0.3 on 2018-03-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20180329_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=1, verbose_name='顺序'),
        ),
    ]
