# Generated by Django 2.0.3 on 2018-03-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180329_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/2018/03/default.png', null=True, upload_to='image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
