# Generated by Django 2.0.3 on 2018-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180330_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
